### ISSUE TITLE
improve adding new projects

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#240] opened 2015-12-09 19:33 UTC
please make adding new project more easier

currently i have to fill the project, hit save and then press "fetch now"
this leads often to invalid  initial fill and crappy versions

----
https://release-monitoring.org/project/8325/
Latest version(s):
 - 6
 - 1.2.6

----

which themselves lead to messages like `Something strange occured, we found that this project has released a version "1.2.6" while we had the latest version at "6"`

also the api returns the biggest version it found (6 in this case), even if the latest fetch fetches correctly "1.2.6"

so, my suggestion is to add "test fetching" to add/edit dialog, so i wouldn't hit save until i'm satisfied with the result.

ps: don't even know how  to get rid of that crappy version "6"!

**Comment by pypingou** [comment] 2015-12-09 21:58
I think this is a duplicate of https://github.com/fedora-infra/anitya/issues/234

**Comment by glensc** [comment] 2015-12-10 10:15
indeed, but this one indirectly asks to cleanup bad version too in specific package ;) or at least directions how to proceed.

**Closed** 2015-12-10 10:15 UTC

**Comment by glensc** [comment] 2015-12-10 10:21
no response how to cleanup bad version? do i really need to open new bug report?

**Comment by pypingou** [comment] 2015-12-10 10:22
You may want to check the project.

**Comment by glensc** [comment] 2015-12-10 10:22
sorry what?

**Comment by pypingou** [comment] 2015-12-10 10:28
I closed this issue because the version that you asked to be removed has been removed (see: https://release-monitoring.org/project/8325/ ) and the implementation to runs a 'test' check has been already done and merged and will be part of the next release.

I do not see anything left to discuss that would require this ticket to remain open.

**Comment by glensc** [comment] 2015-12-10 10:45
there's no info that you removed the bad version, nor is there "official statement" how to proceed with the "bad versions" if such problem appears again.

also what's offcial statement that api returns "biggest version", not "latest" version.

i'd like still get answer to such topics.

**Comment by pypingou** [comment] 2015-12-10 10:47
> there's no info that you removed the bad version, or did it recover itself?

I did it

> nor is there "official statement" how to proceed with the "bad versions" if such problem appears again.

That's why the 'flag' feature was created, same for invalid projects or any actions that admins can do but not regular users.

> also what's offcial statement that api returns "biggest version", not "latest" version.

It returns the latest, according to its sorting not by publishing dates.

**Comment by glensc** [comment] 2015-12-10 10:52
ok. did not know about `Flag` button. i guess there's no real place to put more information to newcomers.
