### ISSUE TITLE
R packages don't seem to get the new tarball

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/anitya#109] opened 2015-03-04 04:19 UTC
See https://bugzilla.redhat.com/show_bug.cgi?id=1198383 

It correctly detected the new version, but the scratch build was with the old tar ball.

**Comment by pypingou** [comment] 2015-03-04 06:49
That is because of the way the Source0 is built: http://pkgs.fedoraproject.org/cgit/R-car.git/tree/R-car.spec#n9

**Comment by ralphbean** [comment] 2015-03-04 11:45
Thanks for reporting @opoplawski.  I'm closing this as a duplicate of fedora-infra/the-new-hotness#29.

**Closed by ralphbean** 2015-03-04 11:45 UTC
