### ISSUE TITLE
Monitoring for the GNU projects doesn't work

### ISSUE THREAD

**Issue by ljavorsk** [fedora-infra/anitya#1577] opened 2023-05-04 12:40 UTC
I've looked into two of my GNU projects:
https://release-monitoring.org/project/353/
https://release-monitoring.org/project/4939/

And both of them failed to retrieve the releases.

If I check manually I can see the releases. Could you please help me find out what is causing this issue?

**Comment by ljavorsk** [comment] 2023-05-04 12:43
I've looked at more GNU projects and all of them have the same issue:
https://release-monitoring.org/project/1251/
https://release-monitoring.org/project/675/

I could find only one which is working properly (GCC), but it may be because it uses Github for the releases and not the ftp.gnu server:
https://release-monitoring.org/project/6502/

**Comment by Zlopez** [comment] 2023-05-05 08:57
This seems like some issue in GNU backend, I need to investigate why the regex is not working anymore on the page.

**Comment by romulasry** [comment] 2023-05-06 20:10
Same issue: https://release-monitoring.org/project/1277/

**Comment by lzaoral** [comment] 2023-05-09 08:20
I see the same error also with `lynx` which is not a GNU project and uses the `folder` backend instead: https://release-monitoring.org/project/1863/

**Comment by xosevp** [comment] 2023-05-09 08:44
It's a  "Default regex" bug: https://github.com/fedora-infra/anitya/issues/1569#issuecomment-1536788547

**Comment by Zlopez** [comment] 2023-05-15 13:39
Closing as duplicate of #1569

**Closed by Zlopez** 2023-05-15 13:39 UTC
Labels: type.bug
