### ISSUE TITLE
added version != retrieved version, and added version is excluded by version filter

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/anitya#1496] opened 2022-10-11 19:36 UTC
I got several wrong Fedora bugs filed by Upstream Release Monitoring (the-new-hotness ?), using corrupted data from release-monitoring.org for some packages that I maintain:

The "retrieved versions" in the filed bugs are "2.28.0", but the version that the bug is actually filed for is "3.0.0-alpha.1", which is 1) not the retrieved version (filing a bug for "2.28.0" would have been correct) and 2) alpha releases are explicitly excluded by the version filter that's set up for those projects:

https://bugzilla.redhat.com/show_bug.cgi?id=2129669#c0
https://bugzilla.redhat.com/show_bug.cgi?id=2129670#c0
https://bugzilla.redhat.com/show_bug.cgi?id=2129671#c0

I already flagged the projects on release-monitoring.org to have the "3.0.0-alpha.1" pre-release that slipped past the version filter removed.

**Comment by Zlopez** [comment] 2022-10-12 07:48
This is actually a great success, till the latest version of the-new-hotness it wasn't able to report version that wasn't considered latest by Anitya and now it will give you heads-up for the latest stable version, even if there is newer pre-release (looking at the package in Fedora the 2.28 is newer than the one that is actually in Fedora). Thanks for letting me know that this is working as intended.

I removed the alpha versions from the projects, if you added it to the filter anyway.

I'm closing the issue, because this works as intended. Hotness is reporting version that is newer than the one in Fedora even if there is newer one in Anitya. If you think there is something that is not working as it should, feel free to reopen the issue.

**Closed by Zlopez** 2022-10-12 07:48 UTC

**Comment by decathorpe** [comment] 2022-10-12 08:56
I can't reopen the issue, but this is definitely not working as intended.

The projects all had a *pre-existing* version filter of `alpha;beta;rc;pre`, and despite that fact, the version `3.0.0-alpha.1` was added to the list of versions. `3.0.0-alpha.1` isn't even the most recent release, that would have been `3.0.0-alpha.2`, in the case of the first bug in the list above. Either way, anitya added a version that was explicitly filtered out to its database, and the one it added wasn't even the latest one.

the-new-hotness then saw that new version and filed a bug for the Fedora package. That part worked fine. The problem is that anitya considered some random version that should have been excluded by the existing version filter as "a new one" (despite it not even being the highest version).

**Comment by Zlopez** [comment] 2022-10-12 09:40
I quickly checked the projects in Anitya and none of them is retrieving alpha versions with current filter. I assume that the version was retrieved before the filter was added, which will not delete it from project. And according to the message in all bugzilla tickets, the `3.0.0-alpha.1` wasn't the one reported, just the one that was considered latest by Anitya. But it's possible that the summary just contains the latest, which will be a bug in the-new-hotness.

In future there should be a notification settings on dist-git to allow you to retrieve only stable versions, but right now it just let's you know when something new is retrieved.

From https://bugzilla.redhat.com/show_bug.cgi?id=2129671
```
Releases retrieved: 2.28.0
Upstream release that is considered latest: 3.0.0-alpha.1
```

**Comment by decathorpe** [comment] 2022-10-12 09:58
> But it's possible that the summary just contains the latest, which will be a bug in the-new-hotness.

That might be it, yes. That would explain the problem with the wrong bug details.

**Comment by Zlopez** [comment] 2022-10-12 11:53
Could you report this on [the-new-hotness](https://github.com/fedora-infra/the-new-hotness)?
