### ISSUE TITLE
why https://release-monitoring.org/project/258035/ was deleted ? or is disappeared ?

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/anitya#1551] opened 2023-02-24 15:13 UTC
it was working well

**Comment by sergiomb2** [comment] 2023-02-25 17:54
https://release-monitoring.org/project/258035/

**Comment by sergiomb2** [comment] 2023-02-25 18:00
I notice that 
https://release-monitoring.org/project/257990/ exist
all from https://release-monitoring.org/project/257991/ to https://release-monitoring.org/project/258035/ don't exist
and https://release-monitoring.org/project/258036 or upper exist again

**Comment by Zlopez** [comment] 2023-02-27 09:26
The projects are deleted only for two reasons:
1) Duplicate of another project, this is done manually by release-monitoring.org admin when solving flags (mappings are moved to one of the projects and the second one is deleted)
2) Automatically, if the projects fails to obtain a new version for 1000 checks (this is configurable) and there is no mapping on the project (this is to prevent spam projects created from PyPi)

So if those projects were deleted, they were probably a duplicate of other project in Anitya or just PyPi spam that didn't exist anymore.

**Comment by sergiomb2** [comment] 2023-02-27 12:03
Hi, 
is not duplicated is another mapping for ImageMagick , I did some magic , but I don't have one copy , and I'd like to have a copy 
can you send me the last configuration of  https://release-monitoring.org/project/258035/ ? 

thank you

**Comment by Zlopez** [comment] 2023-02-27 16:27
Here it is https://apps.fedoraproject.org/datagrepper/v2/id?id=4578a5c0-2a98-4f60-821e-44a1858efcb1&is_raw=true&size=extra-large

You can create another mapping on the existing project, if we are talking about package distribution mapping.

**Comment by sergiomb2** [comment] 2023-02-27 16:37
I need a especial regexp for Fedora 



ImageMagick version is 7.1.0-62 but rpm doesn't allow "-" on release version so I need convert it to 7.1.0.62 

"regex": "([0-9]+)[.]([0-9]+)[.]([0-9]+)-([0-9]+)", do that because only catch the numbers of the version, that did the magick replace of "-" to "." :) 

Thank you for recover the regexp for me

**Closed** 2023-02-27 17:41 UTC
Labels: release-monitoring.org

**Comment by Zlopez** [comment] 2023-02-28 09:12
I know that the-new-hotness has issues with versions like these. It's good to know that this could be a reason for having duplicate of the same project.
