### ISSUE TITLE
release-monitoring.org is not working

### ISSUE THREAD

**Issue by dharanlinux** [fedora-infra/anitya#896] opened 2020-04-03 10:22 UTC
The release-monitoring.org page is not working. Below is the log from the page.
```
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

-     The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
-     The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
-     Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
```
![release-monitoring](https://user-images.githubusercontent.com/47008382/78350563-09b2b280-75c3-11ea-8ad1-0d9ab3e6de84.png)

**Comment by Zlopez** [comment] 2020-04-03 17:05
I checked the instance now and it's running. But the latest instance is running only 6 hours, so there was some outage.

I'm closing this one now, because the issue is gone.

**Closed by Zlopez** 2020-04-03 17:05 UTC
