### ISSUE TITLE
 Dist-Zilla-Plugin-ModuleBuildTiny check fails

### ISSUE THREAD

**Issue by ppisar** [fedora-infra/anitya#1575] opened 2023-05-02 12:47 UTC
<https://release-monitoring.org/project/13960/> shows "failed" status. Going to Edit → Test check reports:

~~~
Unable to retrieve the latest version from upstream!
ERROR: "Error when checking for new version: Dist-Zilla-Plugin-ModuleBuildTiny: invalid regular expression"
~~~

**Comment by Zlopez** [comment] 2023-05-02 16:50
Duplicate of https://github.com/fedora-infra/anitya/issues/1569

**Closed as completed by Zlopez** 2023-05-02 16:50 UTC
