### ISSUE TITLE
Handle projects that release multiple packages

### ISSUE THREAD

**Issue by tyll** [fedora-infra/anitya#80] opened 2015-02-19 20:53 UTC
https://www.xine-project.org/releases release for example xine-lib and gxine at sourceforge. For the sourceforge backend to work, the project name needs to be xine for both and the sourceforge name can be xine-lib and gxine. However if both projects are called xine, they are not allowed to have the same homepage:

https://release-monitoring.org/project/5543/
https://release-monitoring.org/project/5558/

Also the conversion from the wiki did not work properly for the 5543 xine project, because the sourceforge name contained the full line from the wiki - or it was a human error and someone entered the wrone value there.

**Comment by glensc** [comment] 2015-02-19 22:44
the same problem exists for nagios (sf project=nagios, tarball names=nagios, nrpe), which was discussed in irc few months ago. some ideas were exchanged but nothing concluded. sorry no log now, but can dig up if needed.

**Comment by robert-scheck** [comment] 2015-02-21 04:02
I guess my issue with phpMyAdmin is similar: There is phpMyAdmin 4.3.x (current stable branch) being mapped at Fedora to phpMyAdmin, but they still maintain phpMyAdmin 4.0.x which needs to be mapped for Fedora EPEL to phpMyAdmin4.

**Comment by glensc** [comment] 2015-02-21 21:13
you can map same distro twice! just add it's all packages! not sure is this intended by design, but it works now.

**Comment by robert-scheck** [comment] 2015-02-22 01:24
@glensc: I am sorry, but I can not see how your suggestion would solve my issue: I need to map different upstream branches to different distribution packages. Right now, I only can map one upstream branch (latest or whatever is catched) to multiple distribution packages.

**Comment by siwinski** [comment] 2015-02-22 04:53
Same issue for Drupal pkgs that exist for both Drupal 7 and Drupal 6.  Drupal provides latest version info and downloads to both base pkg versions from the same URL.  For example, [drupal6-ctools](https://release-monitoring.org/project/593/) and [drupal7-ctools](https://release-monitoring.org/project/523/) homepage URL is https://www.drupal.org/project/ctools but only one pkg is allowed to have the homepage URL in Anitya.

**Comment by siwinski** [comment] 2015-02-22 06:01
I believe I have found a workaround for the Drupal packages.  If I prefix the Anitya project name with either "Drupal 6: " or "Drupal 7: " then both Anitya projects can have the same homepage URL.  That also has the added benefit that I do not have to go to the Anitya project detail page to check if the project is for Drupal 6 or 7.  Perhaps it would help if a "group" could be added and then instead of just name/homepage uniqueness there would be group/name/homepage uniqueness.

**Comment by glensc** [comment] 2015-02-22 23:13
@robert-scheck  sorry, it was not solution to your problem rather outlining existing issues to anitya maintainers :)

**Comment by pypingou** [comment] 2015-02-24 15:30
For drupal projects: https://github.com/fedora-infra/anitya/pull/93 (merged)

**Comment by siwinski** [comment] 2015-02-24 15:32
THANKS @pypingou !

**Comment by pypingou** [comment] 2015-02-25 10:29
Ok I tried to summarize a little the situation and problem here: http://blog.pingoured.fr/index.php?post/2015/02/25/About-SourceForge-and-anitya

**Comment by scop** [comment] 2015-02-25 20:55
I feel more comfortable replying here than commenting in the blog, so here goes:

One approach could be to make the SF project name configurable, in addition to the current project and tarball names. If unset, both SF project and tarball names would default to the Anitya project name.

Another would be to introduce the concept of packages under the project: the project would be an umbrella and would hold the homepage URL, packages would be configured below it and for the SF case the parent project would determine the RSS URL name, and the tarball name would come from the package. Distro mappings would be done on package level.

Yet another way would be to forget about projects entirely, and just operate on packages (or tarballs, deliverables, whatever good name you can come up with for it...). So if a SF project A releases packages B, C, and D, what we configure in Anitya is three things: B, C, and D. This is basically what we had in cnucnu and I think it worked just fine (well there the package name was an actual Fedora package name but that's an irrelevant extra propertly wrt this). Well, this is kind of the same thing as my first suggestion above.

**Closed** 2015-05-03 13:34 UTC

**Comment by glensc** [comment] 2015-05-03 16:02
:+1:  finally!

**Comment by pypingou** [comment] 2015-05-06 10:43
This is now live and I went through the project that failed to update and are related to SF to try to fix them
