### ISSUE TITLE
Anitya seems to have missed pymongo's 3.3.1 release

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/anitya#385] opened 2016-11-25 19:50 UTC
pymongo does have a 3.3.1 release from October 26:

https://github.com/mongodb/mongo-python-driver/releases/tag/3.3.1

However, Anitya did not notice the release, and only knows about the 3.3.0 and 3.4rc0 releases:

https://release-monitoring.org/project/8822/

**Comment by akien-mga** [comment] 2016-11-25 20:03
I don't think that's a bug. 3.4rc0 was released before 3.3.1, and is evaluated as a newer version, so 3.3.1 is not added as newer release.

**Comment by bowlofeggs** [comment] 2016-11-26 04:04
Perhaps we can adjust this issue to be a feature request instead? It's not uncommon for some projects to support multiple releases at once. Django is an example - they maintain an LTS release alongside their normal release cycles. It would be nice if Anitya/the-new-hotness could still notify developers when situations like that (or like pymongo) happen.

**Comment by jeremycline** [comment] 2016-12-09 16:13
Closing as a duplicate of https://github.com/fedora-infra/anitya/issues/269 (but I do agree, this would be nice)

**Closed by jeremycline** 2016-12-09 16:13 UTC
Labels: enhancement
